### PR TITLE
fix: exclude messages field from Datastore index to avoid 1500 bytes limit

### PR DESCRIPTION
**Pull request by cymarechal-devoteam**
Hi,

While playing around with DatastoreChatMessageHistory, I noticed that I quickly ran into Datastore's 1,500 bytes limit for indexed string property's UTF-8 encoding (source: https://cloud.google.com/datastore/docs/concepts/limits).

This PR creates a simple test case to demonstrate the issue and solves it by using Datastore's `exclude_from_indexes` parameter.

Feedback appreciated!

### CODE REVIEW

**Comment by cymarechal-devoteam** [comment]
Hi @averikitsch,
Thank you for interacting!
I see some integration tests have failed. Is there any way I can help on those?

**Comment by averikitsch** [comment]
@JU-2094 is currently out of office and will review next week. Thanks!

**Review by JU-2094 — APPROVED** [review]
Awesome, lgtm!

**Review by averikitsch — APPROVED** [review]

**Comment by averikitsch** [comment]
@cymarechal-devoteam can you resolve the merge conflicts?

**Comment by cymarechal-devoteam** [comment]
> @cymarechal-devoteam can you resolve the merge conflicts?

That should be it! Please let me know if there is anything else.

**Pull request merged**
